Enh/account 4
mui/toolpad pull request #4227
Opened 2024-10-07 08:46 UTC by bharatkashyap

- Close #4226 
- Add a `userDetailsContainer` slot to override user details section completely
- Add docs example
<img width="871" alt="Screenshot 2024-10-07 at 2 16 07 PM" src="https://github.com/user-attachments/assets/652f56fb-c5f8-47b1-b3e1-43273c2dce58">

2024-10-07 18:10 UTC, apedroferreira requested changes
Looks great!
Other than what I added in https://github.com/mui/toolpad/pull/4181# just added some opinions on naming and docs feedback.

2024-10-07 18:10 UTC, apedroferreira commented on packages/toolpad-core/src/DashboardLayout/DashboardLayout.tsx
> +        content: PropTypes.elementType,
Maybe the name `content` is too generic, but it's just my opinion, I don't mind it.

2024-10-07 18:10 UTC, apedroferreira commented on packages/toolpad-core/src/Account/Account.tsx
> +              padding: theme.spacing(2),
Is using a simple `2` here not the same thing? (not sure though)

2024-10-07 18:10 UTC, apedroferreira commented on docs/data/toolpad/core/components/account/account.md
> +// ...
This example doesn't immediately make sense to me: where is the `CustomSession` being used?

2024-10-22 16:06 UTC, apedroferreira approved these changes
Looks great, really easy to understand!
Added some small documentation suggestions.

2024-10-22 16:06 UTC, apedroferreira commented on docs/data/toolpad/core/components/use-session/use-session.md
> +const session = useSession();
Should we show where to import it from here too?

2024-10-29 21:53 UTC, aress31 commented
I believe that useSession should return both session and setSession. In many parts of an application, such as the SignInPage, a successful sign-in requires setting the session. Currently, this can only be done at the top level in the AppProvider, forcing the setter to be passed down multiple levels through the component hierarchy. Allowing this hook to both read and update the session directly would significantly expand its usability across various use cases.

2024-10-30 15:37 UTC, bharatkashyap commented
> I believe that `useSession` should return both session and `setSession`. In many parts of an application, such as the `SignInPage`, a successful sign-in requires setting the session. Currently, this can only be done at the top level in the `AppProvider`, forcing the setter to be passed down multiple levels through the component hierarchy. Allowing this hook to both read and update the session directly would significantly expand its usability across various use cases.

I'll update the original issue you created with this and we can track this as a feature request to be discussed and potentially added (or not) to the roadmap - let me know if that's okay

2024-10-30 15:39 UTC, merged