Add hideNavigation prop
mui/toolpad pull request #4231
Opened 2024-10-08 16:08 UTC by vikasgurjar

Closes #4229

- [ ] I've read and followed the [contributing guide](https://github.com/mui/toolpad/blob/master/CONTRIBUTING.md#sending-a-pull-request) on how to create great pull requests.
- [ ] I've updated the relevant documentation for any new or updated feature.
- [ ] I've linked relevant GitHub issue with "Closes #<issue id>".
- [ ] I've added a visual demonstration in the form of a screenshot or video.

2024-10-08 17:22 UTC, apedroferreira requested changes
Looks perfect, thank you! And that's exactly what I meant with the demo, good job finding it! :)
Just a few really minor changes suggested.

Also for the docs changes you can run:
`pnpm proptypes` to generate proptypes the be read by the API documentation
`pnpm docs:build:api` to build the API docs
`pnpm docs:typescript:formatted` to format all the docs files based on the .js file

2024-10-08 17:22 UTC, apedroferreira commented on packages/toolpad-core/src/DashboardLayout/DashboardLayout.tsx
> +      {!hideNavigation && <React.Fragment>
`React.Fragment` not needed?

2024-10-08 17:22 UTC, apedroferreira commented on packages/toolpad-core/src/DashboardLayout/DashboardLayout.tsx
> +  * If the navigation bar and button should to be hidden
Can we rephrase it to `Whether the navigation bar and menu icon should be hidden`?

2024-10-08 17:22 UTC, apedroferreira commented on packages/toolpad-core/src/DashboardLayout/DashboardLayout.tsx
> +      if (hideNavigation) {
There's also a `marginRight` on the boxes around these icons that we should not have if they're not shown.
So instead on line 566 we can probably have something like:

```tsx
{!hideNavigation ? 
         <Box
            sx={{
              mr: { sm: disableCollapsibleSidebar ? 0 : 1 },
              display: { md: 'none' },
            }}
          >
            {getMenuIcon(isMobileNavigationExpanded)}
          </Box>
          <Box
            sx={{
              display: { xs: 'none', md: disableCollapsibleSidebar ? 'none' : 'block' },
              mr: disableCollapsibleSidebar ? 0 : 1,
            }}
          >
            {getMenuIcon(isDesktopNavigationExpanded)}
          </Box> : null}
```

2024-10-08 17:22 UTC, apedroferreira commented on packages/toolpad-core/src/DashboardLayout/DashboardLayout.tsx
> +      {!hideNavigation && <React.Fragment>
Also can we write it like `{!hideNavigation ? ... : null}`? Just because we've been following that convention in the project.

2024-10-08 17:22 UTC, apedroferreira commented on packages/toolpad-core/src/DashboardLayout/DashboardLayout.test.tsx
> +    // Expect that the navigation and toggle button is not rendered
```suggestion
    // Expect that the navigation and toggle button are not rendered
```

2024-10-08 17:22 UTC, apedroferreira commented on docs/data/toolpad/core/components/dashboard-layout/dashboard-layout.md
> +The layout sidebar can be hidden if needed using the `hideNavigation` prop.
```suggestion
The layout sidebar can be hidden if needed with the `hideNavigation` prop.
```

2024-10-08 17:29 UTC, apedroferreira commented on docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutSidebarHidden.js
> +const NAVIGATION = [];
We can just not pass this as it defaults to []

2024-10-08 17:30 UTC, apedroferreira commented on docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutSidebarHidden.js
> +
empty line

2024-10-08 17:31 UTC, apedroferreira commented on docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutSidebarHidden.js
> +  const router = React.useMemo(() => {
No need to pass a router in this example too I think.

2024-10-08 17:32 UTC, apedroferreira commented on docs/data/toolpad/core/components/dashboard-layout/DashboardLayoutSidebarHidden.js
> +    // preview-start
You can remove `// preview-start` and `// preview-end` here and the code preview will show only the DashboardLayout which is the most important information.

2024-10-09 06:14 UTC, vikasgurjar commented
@apedroferreira I will need your help with the `test_static` build issue. Due to some conf mismatch I'm not able to fix the above issue. Can you guide on how to fix it?

2024-10-09 10:43 UTC, apedroferreira commented
> @apedroferreira I will need your help with the `test_static` build issue. Due to some conf mismatch I'm not able to fix the above issue. Can you guide on how to fix it?

Can you run `pnpm docs:typescript:formatted`? That should do it.
Everything looks great btw, thanks for the changes!

2024-10-09 12:50 UTC, vikasgurjar commented
> > @apedroferreira I will need your help with the `test_static` build issue. Due to some conf mismatch I'm not able to fix the above issue. Can you guide on how to fix it?
> 
> Can you run `pnpm docs:typescript:formatted` from the project root? That should do it. Everything looks great btw, thanks for the changes!

I have done that multiple times now. I'm running it on windows, not really what's wrong here, can it be new line char issue or formatter issue?

2024-10-09 13:49 UTC, apedroferreira commented
> > > @apedroferreira I will need your help with the `test_static` build issue. Due to some conf mismatch I'm not able to fix the above issue. Can you guide on how to fix it?
> > 
> > 
> > Can you run `pnpm docs:typescript:formatted` from the project root? That should do it. Everything looks great btw, thanks for the changes!
> 
> I have done that multiple times now. I'm running it on windows, not really what's wrong here, can it be new line char issue or formatter issue?

I see, when I run `pnpm docs:typescript:formatted` (`docs/scripts/formattedTSDemos` script) on my Macbook there's a difference in the `DashboardLayoutSidebarHidden.tsx.preview` file compared to your current PR... Might be an OS thing, maybe line endings.

@mui/docs-infra any knowledge on this issue? Is it an issue with the script? We're generally using the same script as https://github.com/mui/material-ui/blob/master/docs/scripts/formattedTSDemos.js.

2024-10-09 14:17 UTC, Janpot commented
The line endings don't match. Maybe you hit "save" on the preview and the auto-formatter kicked in?

2024-10-09 14:36 UTC, vikasgurjar commented
> The line endings don't match. Maybe you hit "save" on the preview and the auto-formatter kicked in?

There was no need to hit the save. Seems like some other issue. Even your commit didn't help here

2024-10-09 15:30 UTC, Janpot commented
It did fix it, CI just found another issue, still had to run `pnpm prettier`.

2024-10-09 15:31 UTC, vikasgurjar commented
> It did fix it, CI just found another issue, still had to run `pnpm prettier`.

Great, Thanks! I was setting up WSL in my windows machine, to try fixing this

2024-10-09 16:10 UTC, apedroferreira commented
Ok, let me know if you ever find what the issue was! Just added some small demo changes and will merge :)

2024-10-09 16:10 UTC, apedroferreira approved these changes

2024-10-09 16:27 UTC, merged