fix: hasDrawerTransition's logics
mui/toolpad pull request #4522
Opened 2024-12-08 20:39 UTC by gil-obradors

Closes #4511 

Disable the CSS transitions only for the temporary sidebar that shows on mobile devices, but also not needed when CollapsibleSidebar is disabled.

- [x] I've read and followed the [contributing guide](https://github.com/mui/toolpad/blob/master/CONTRIBUTING.md#sending-a-pull-request) on how to create great pull requests.
- [ ] I've updated the relevant documentation for any new or updated feature.
- [x] I've linked relevant GitHub issue with "Closes #<issue id>".
- [x] I've added a visual demonstration in the form of a screenshot or video.

https://github.com/user-attachments/assets/1353c8a0-2179-467a-8fa8-68be5f1d6891

2024-12-11 13:54 UTC, apedroferreira requested changes

2024-12-11 14:00 UTC, apedroferreira commented on packages/toolpad-core/src/DashboardLayout/DashboardLayout.tsx
> +  const hasDrawerTransitions = isOverSmViewport && !disableCollapsibleSidebar;
My first suggestions was incorrect, the new one should be good!
Sorry if it caused any confusion.

2024-12-11 16:56 UTC, Janpot commented
How hard would it be to add coverage for this in a test?

2024-12-11 17:01 UTC, apedroferreira commented
> How hard would it be to add coverage for this in a test? Ideally we aim for adding tests when we fix bugs and especially regressions.

Probably quite difficult here as it's related to CSS transitions, which could also mean it's not a major issue that needs to be covered by tests...

2024-12-11 17:04 UTC, Janpot commented
> Unless some kind of visual snapshots can be taken during the transition, maybe we could try that.

No, don't worry in that case. Let's not waste time on it right now.

2025-01-07 12:19 UTC, apedroferreira approved these changes

2025-01-07 12:19 UTC, merged