[cli] Add framework selection to support Vite
mui/toolpad pull request #4545
Opened 2024-12-18 16:28 UTC by bharatkashyap

- Closes #4235

2024-12-24 16:01 UTC, apedroferreira requested changes
Looks good, just some general suggestions, nothing too specific to the implementation that I could notice!

2024-12-30 08:29 UTC, bharatkashyap commented on packages/create-toolpad-app/src/index.ts
> +    if (frameworkOption === 'nextjs') {
My preference would be to keep the options list short, so Next.js or Vite? -> App Router or Pages Router?

2024-12-30 08:29 UTC, bharatkashyap commented on examples/core/auth-vite/README.md
> +This example provides a minimal setup to get Toolpad Core working in Vite with HMR, as well as routing with React Router and a mock authentication setup.
I feel like it's okay to preserve the barebones example just to demonstrate the minimum requirements to get auth working

2025-01-07 13:50 UTC, apedroferreira approved these changes

2025-01-10 12:34 UTC, merged