[Account] Prevent account info overflowing on kebab menu
mui/toolpad pull request #4555
Opened 2024-12-24 09:13 UTC by bharatkashyap

- Closes https://github.com/mui/toolpad/issues/4552
- A simple `overflow="hidden"` does the trick 
- The `AccountPreview` will truncate the account info if placed inside a div with a set width, otherwise will expand

<img width="663" alt="Screenshot 2025-01-08 at 7 14 25 PM" src="https://github.com/user-attachments/assets/02860592-4a38-4e93-baf4-9c2c31707a3c" />

- https://deploy-preview-4555--mui-toolpad-docs.netlify.app/toolpad/core/react-dashboard-layout/#examples

2025-01-06 15:55 UTC, apedroferreira requested changes
Added just one comment, I guess at least having an ellipsis even when there's no options button should be doable for consistency?

2025-01-06 15:55 UTC, apedroferreira commented on packages/toolpad-core/src/Account/AccountPreview.tsx
> +              maxWidth={handleClick ? 180 : 'unset'}
Looks good, but is there no way to make it overflow with the available width without us having to set a manual value?
I feel like it should be possible but haven't tried it.

Also what is the behavior if there is no options button? Does it truncate with an ellipsis after the sidebar width? I guess that's what it should do in every case...

2025-01-07 10:31 UTC, bharatkashyap commented on packages/toolpad-core/src/Account/AccountPreview.tsx
> +              maxWidth={handleClick ? 180 : 'unset'}
The idea to only truncate when there is an options button is to allow the popover to have the complete information, so something like:

https://github.com/user-attachments/assets/9848b2ee-becf-401e-b3a6-fb35a32a923d

We could truncate in all cases, but then do you suggest including a Tooltip when the text is inside the popover; something like: 

https://github.com/user-attachments/assets/37583309-75c9-45b2-9529-28a8f9715f36

2025-01-07 10:45 UTC, apedroferreira commented on packages/toolpad-core/src/Account/AccountPreview.tsx
> +              maxWidth={handleClick ? 180 : 'unset'}
I meant that if you don't pass a `handleClick` and so there's no options button to show a popover, this is what it looks right now:

<img width="837" alt="Screenshot 2025-01-07 at 10 44 02" src="https://github.com/user-attachments/assets/82c4ab19-fdaf-4e8f-a216-4f834fdd134e" />

So maybe all these overflows should ellipsize automatically? Probably not a huge deal though, it was just something I noticed.

2025-01-07 11:10 UTC, bharatkashyap commented on packages/toolpad-core/src/Account/AccountPreview.tsx
> +              maxWidth={handleClick ? 180 : 'unset'}
Ah got it! Yes the ellipsis should happen in this case as well, good catch

2025-01-09 22:18 UTC, apedroferreira approved these changes
Nice, thanks for the changes, looks like there was a better solution after all! I wasn't 100% sure.

2025-01-10 06:15 UTC, merged