Update PageHeader.tsx
mui/toolpad pull request #4571
Opened 2024-12-29 04:40 UTC by null93

- [ ] I've read and followed the [contributing guide](https://github.com/mui/toolpad/blob/master/CONTRIBUTING.md#sending-a-pull-request) on how to create great pull requests.
- [ ] I've updated the relevant documentation for any new or updated feature.
- [ ] I've linked relevant GitHub issue with "Closes #<issue id>".
- [ ] I've added a visual demonstration in the form of a screenshot or video.

2025-01-06 11:22 UTC, Janpot commented on packages/toolpad-core/src/PageContainer/PageHeader.tsx
> +                <Typography key={item.title} color="text.primary">
Let's use the `map` index here instead. We don't necessarily expect `title` to be uniqye

2025-01-07 04:34 UTC, null93 commented on packages/toolpad-core/src/PageContainer/PageHeader.tsx
> +                <Typography key={item.title} color="text.primary">
Great thinking! Done!

2025-01-07 07:41 UTC, Janpot approved these changes

2025-01-07 07:46 UTC, Janpot requested changes
Sorry, approved too fast. Let's use the same key everywhere. Also, can the `path` property be made optional now in the `BreadCrumb` [type](https://github.com/mui/toolpad/blob/b9962d1ec3a3407c283267da07a5afd41d454cbe/packages/toolpad-core/src/PageContainer/PageContainer.tsx#L18)?

2025-01-07 07:46 UTC, Janpot commented on packages/toolpad-core/src/PageContainer/PageHeader.tsx
>                    key={item.path}
```suggestion
                  key={index}
```

2025-01-08 20:56 UTC, Janpot approved these changes
Looks great, thank you!

2025-01-09 09:17 UTC, merged